# generated by datamodel-codegen:
#   filename:  analytics.schema.json
#   timestamp: 2026-04-15T10:05:36+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, Field


class Status(str, Enum):
    pass_ = 'pass'
    fail = 'fail'
    warning = 'warning'
    bonus = 'bonus'
    not_disclosed = 'not_disclosed'
    n_a = 'n_a'


class Significance(str, Enum):
    HIGH = 'HIGH'
    MEDIUM = 'MEDIUM'
    LOW = 'LOW'


class Category(str, Enum):
    Financial_Health = 'Financial Health'
    Governance = 'Governance'
    Impact_Awareness = 'Impact Awareness'
    Risk_Management = 'Risk Management'
    Transparency = 'Transparency'


class Details(BaseModel):
    formula: str = Field(..., description='The generic formula used for the check.')
    calculation: str = Field(
        ..., description='The specific calculation with values for this charity.'
    )
    elaboration: str | None


class CheckItem(BaseModel):
    id: str = Field(
        ..., description="Unique slug for the check-item (e.g., 'check_reserve_cap')."
    )
    status: Status = Field(..., description='The result status of the check.')
    significance: Significance = Field(
        ..., description='The priority or importance of the check.'
    )
    category: Category = Field(..., description='The domain of the audit check.')
    details: Details = Field(
        ..., description='Transparent details about how the result was obtained.'
    )


class ConfidenceTier(str, Enum):
    HIGH = 'HIGH'
    MEDIUM = 'MEDIUM'
    LOW = 'LOW'


class Details1(BaseModel):
    formula: str
    calculation: str


class CalculatedMetric(BaseModel):
    id: str = Field(
        ..., description="Unique slug for the metric (e.g., 'cost_per_outcome')."
    )
    name: str = Field(
        ...,
        description="Human-readable name for the metric (e.g., 'Cost Per Outcome').",
    )
    value: float | str | list[Any] | None = Field(
        ..., description='The calculated value of the metric.'
    )
    confidence_tier: ConfidenceTier = Field(
        ..., description='The confidence level of the calculated metric.'
    )
    confidence_note: str = Field(
        ..., description='An explanation of how the confidence tier was determined.'
    )
    details: Details1 = Field(
        ..., description='Transparent details about how the result was obtained.'
    )


class Outcome(BaseModel):
    value: float | None = None
    source_quote: str | None = None


class WSpecies(BaseModel):
    key: str | None = None
    value: float | None = None
    source: str | None = None


class WLeverage(BaseModel):
    key: str | None = None
    value: float | None = None
    source: str | None = None


class DEvidence(BaseModel):
    key: str | None = None
    value: float | None = None
    source: str | None = None


class BreakdownItem(BaseModel):
    metric_name: str | None = None
    outcome: Outcome | None = None
    w_species: WSpecies | None = None
    w_leverage: WLeverage | None = None
    d_evidence: DEvidence | None = None
    claimed_ies_i: float | None = Field(
        None,
        description='The claimed IES for this individual metric, before epistemic discounts.',
    )
    ies: float | None = None
    calculation: str | None = None


class Details2(BaseModel):
    breakdown: list[BreakdownItem] | None = Field(
        None,
        description='A detailed breakdown of the IES calculation for each individual impact metric.',
    )


class IesMetric(CalculatedMetric):
    id: Literal['impact_equivalency_score']
    claimed_ies: int = Field(
        ...,
        description='The Impact Equivalency Score (IES) calculated without epistemic discounts.',
    )
    evaluated_ies: int = Field(
        ...,
        description='The Impact Equivalency Score (IES) calculated with epistemic discounts applied.',
    )
    details: Details2
    confidence_tier: ConfidenceTier = Field(
        ..., description='The confidence level of the calculated metric.'
    )
    confidence_note: str = Field(
        ..., description='An explanation of how the confidence tier was determined.'
    )


class Analytics(BaseModel):
    check_items: list[CheckItem] = Field(
        ..., description='A list of audit check-item results.'
    )
    calculated_metrics: list[IesMetric | CalculatedMetric] = Field(
        ..., description='A list of informational metrics derived from the audit.'
    )
