from pydantic import BaseModel, Field
from typing import List, Literal, Optional

Significance = Literal["HIGH", "MEDIUM", "LOW"]
Status = Literal["pass", "fail", "warning", "null"]
Category = Literal[
    "Financial Health",
    "Governance",
    "Impact Awareness",
    "Risk Management"
]

class AuditDetails(BaseModel):
    """Transparent details about how the result was obtained."""
    formula: str
    calculation: str
    # source_snippets are omitted as they are not generated by this service

class AuditCheckItem(BaseModel):
    """A single audit check-item result."""
    id: str
    status: Status
    significance: Significance
    category: Category
    details: AuditDetails

class AuditResult(BaseModel):
    """The complete audit result, containing a list of check items."""
    analytics: List[AuditCheckItem]