# generated by datamodel-codegen:
#   filename:  financials.schema.json
#   timestamp: 2026-03-17T07:45:29+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AnyUrl, BaseModel, Field


class Currency(BaseModel):
    original_code: str = Field(
        ...,
        description='The 3-letter ISO 4217 code of the original currency from the report (e.g., HKD, INR, USD).',
    )
    usd_exchange_rate: float | None = Field(
        ...,
        description='The exchange rate to convert 1 unit of the original currency to USD.',
    )
    rate_date: str | None = Field(
        ..., description='The date (YYYY-MM-DD) for which the exchange rate is valid.'
    )


class SourceType(str, Enum):
    attached_report = 'attached_report'
    web_search = 'web_search'


class Source(BaseModel):
    source_type: SourceType = Field(
        ..., description='The strict category of the source document.'
    )
    source_index: int | None = Field(
        None,
        description='For attached PDF document sources, the 0-based index of the attached document (among all attached documents) where the data was found.',
    )
    page_number: int | None = Field(
        None,
        description='For attached PDF document sources, the 1-based absolute index of the page (in that attached document) where the data was found.',
    )
    search_result_index: int | None = Field(
        None,
        description='For web_search sources, the 0-based index of the search result snippet used.',
    )
    quote: str | None = Field(
        ...,
        description='The exact verbatim wording quoted from the source, used for verification and text-fragment generation.',
    )
    resolved_url: AnyUrl | None = Field(
        ...,
        description='The fully resolved deep-link URL (e.g., with #page=N or #:~:text=...) to the specific source evidence. This is populated programmatically.',
    )


class FinancialFigure(BaseModel):
    value: float | None
    source: Source | None = None


class Income(BaseModel):
    donations: FinancialFigure = Field(
        ..., description='Voluntary contributions, sponsorships, or public donations.'
    )
    government_grants: FinancialFigure = Field(
        ...,
        description='Total SWD subvention, including LSG, Rent & Rates, and Central Items.',
    )
    total: FinancialFigure = Field(
        ..., description='Total Revenue/Income for the year.'
    )


class Expenditure(BaseModel):
    administration: FinancialFigure = Field(
        ...,
        description="Overhead, 'Central Administrative Costs', or 'Management/General Office' expenses.",
    )
    fundraising: FinancialFigure = Field(
        ...,
        description='Costs related to appeals, flag days, or donation solicitations.',
    )
    program_services: FinancialFigure = Field(
        ..., description='Costs directly attributed to welfare services.'
    )
    total: FinancialFigure = Field(
        ..., description='Total Expenditure/Expenses for the year.'
    )


class LsgSpecifics(BaseModel):
    lsg_reserve_amount: FinancialFigure
    provident_fund_reserve: FinancialFigure


class Reserves(BaseModel):
    total_reserves: FinancialFigure = Field(
        ..., description='Total unrestricted reserves or fund balance at year end.'
    )


class RatioInputs(BaseModel):
    monthly_operating_expenses: FinancialFigure
    net_current_assets: FinancialFigure
    current_assets: FinancialFigure
    current_liabilities: FinancialFigure


class Financials(BaseModel):
    financial_year: str = Field(
        ..., description="The financial year of the report, e.g., '2024-25'."
    )
    currency: Currency = Field(
        ...,
        description='Details about the original currency and its exchange rate to USD.',
    )
    income: Income = Field(..., description='Breakdown of income sources.')
    expenditure: Expenditure = Field(..., description='Breakdown of expenditures.')
    lsg_specifics: LsgSpecifics = Field(
        ..., description='Lump Sum Grant (LSG) specific figures.'
    )
    reserves: Reserves = Field(
        ..., description='General reserves for non-subvented charities.'
    )
    ratio_inputs: RatioInputs = Field(
        ..., description='Inputs for calculating financial ratios.'
    )
