# generated by datamodel-codegen:
#   filename:  impact_transparency.schema.json
#   timestamp: 2026-04-21T15:13:26+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AnyUrl, BaseModel, Field


class SourceType(str, Enum):
    attached_report = 'attached_report'


class Source(BaseModel):
    source_type: SourceType = Field(
        ..., description='The strict category of the source document.'
    )
    source_index: int = Field(
        ...,
        description='For attached PDF document sources, the 0-based index of the attached document (among all attached documents) where the data was found.',
    )
    page_number: int = Field(
        ...,
        description='For attached PDF document sources, the 1-based absolute index of the page (in that attached document) where the data was found.',
    )
    quote: str | None = Field(
        ...,
        description='The exact verbatim wording quoted from the source, used for verification and text-fragment generation.',
    )
    resolved_url: AnyUrl | None = Field(
        ...,
        description='The fully resolved deep-link URL (e.g., with #page=N or #:~:text=...) to the specific source evidence. This is populated programmatically.',
    )


class UnintendedConsequencesReported(BaseModel):
    value: bool | None = None
    source: Source | None = None


class EuthanasiaStatisticsReported(BaseModel):
    value: bool | None = None
    source: Source | None = None


class TransparencyIndicators(BaseModel):
    unintended_consequences_reported: UnintendedConsequencesReported | None = None
    euthanasia_statistics_reported: EuthanasiaStatisticsReported | None = None


class ImpactTranspar(BaseModel):
    transparency_indicators: TransparencyIndicators = Field(
        ...,
        description='Indicators of operational transparency and epistemic humility.',
    )
