# generated by datamodel-codegen:
#   filename:  impact_metrics.schema.json
#   timestamp: 2026-04-17T08:19:46+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AnyUrl, BaseModel, Field


class QuantitativeData(BaseModel):
    value: float | None
    unit: str
    unit_is_individual_animal: bool | None = Field(
        None,
        description="Whether the unit refers to an individual animal (e.g., 'lives saved', 'vaccinations administered') or a different quantity (e.g., 'tons of feed saved', 'fund raised', 'eggs laid'). This is important for accurate aggregation and comparison across metrics.",
    )


class CounterfactualBaseline(BaseModel):
    description: str
    value: float | None = None


class EvidenceQuality(str, Enum):
    RCT_Meta_Analysis = 'RCT/Meta-Analysis'
    Quasi_Experimental = 'Quasi-Experimental'
    Pre_Post = 'Pre-Post'
    Anecdotal = 'Anecdotal'
    None_ = 'None'


class Timeframe(str, Enum):
    annual = 'annual'
    cumulative = 'cumulative'
    unspecified = 'unspecified'


class SourceType(str, Enum):
    attached_report = 'attached_report'
    web_search = 'web_search'


class Source(BaseModel):
    source_type: SourceType = Field(
        ..., description='The strict category of the source document.'
    )
    source_index: int | None = Field(
        None,
        description='For attached PDF document sources, the 0-based index of the attached document (among all attached documents) where the data was found.',
    )
    page_number: int | None = Field(
        None,
        description='For attached PDF document sources, the 1-based absolute index of the page (in that attached document) where the data was found.',
    )
    search_result_index: int | None = Field(
        None,
        description='For web_search sources, the 0-based index of the search result snippet used.',
    )
    quote: str | None = Field(
        ...,
        description='The exact verbatim wording quoted from the source, used for verification and text-fragment generation.',
    )
    resolved_url: AnyUrl | None = Field(
        ...,
        description='The fully resolved deep-link URL (e.g., with #page=N or #:~:text=...) to the specific source evidence. This is populated programmatically.',
    )


class Metric(BaseModel):
    metric_name: str
    quantitative_data: QuantitativeData
    context_qualifier: str
    counterfactual_baseline: CounterfactualBaseline
    evidence_quality: EvidenceQuality
    timeframe: Timeframe
    source: Source | None


class ImpactMetrics(BaseModel):
    metrics: list[Metric] = Field(
        ...,
        description='A list of specific, quantifiable impact metrics, sorted in descending order of significance.',
    )
