# generated by datamodel-codegen:
#   filename:  impact_interventions.schema.json
#   timestamp: 2026-04-23T06:53:16+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AnyUrl, BaseModel, Field


class Value(str, Enum):
    pure_animal_advocacy = 'pure_animal_advocacy'
    multi_domain_operations = 'multi_domain_operations'


class SourceType(str, Enum):
    attached_report = 'attached_report'


class Source(BaseModel):
    source_type: SourceType = Field(
        ..., description='The strict category of the source document.'
    )
    source_index: int = Field(
        ...,
        description='For attached PDF document sources, the 0-based index of the attached document (among all attached documents) where the data was found.',
    )
    page_number: int = Field(
        ...,
        description='For attached PDF document sources, the 1-based absolute index of the page (in that attached document) where the data was found.',
    )
    quote: str | None = Field(
        ...,
        description='The exact verbatim wording quoted from the source, used for verification and text-fragment generation.',
    )
    resolved_url: AnyUrl | None = Field(
        ...,
        description='The fully resolved deep-link URL (e.g., with #page=N or #:~:text=...) to the specific source evidence. This is populated programmatically.',
    )


class OperatingScope(BaseModel):
    value: Value | None = None
    source: Source | None = None


class ExplicitUnitCost(BaseModel):
    intervention_type: str = Field(
        ...,
        description='The intervention key for leverage multiplier lookup. [ALLOWED VALUES: {{CONCATENATED_INTERVENTION_KEY_VALUES}}]',
    )
    amount: float | None
    currency: str | None
    description: str | None
    source: Source | None


class Context(BaseModel):
    operating_scope: OperatingScope
    explicit_unit_costs: list[ExplicitUnitCost] = Field(
        ...,
        description='Array of unit costs explicitly stated by the charity, each linked to a specific intervention type.',
    )


class ImpactInterventions(BaseModel):
    context: Context
