# generated by datamodel-codegen:
#   filename:  impact.schema.json
#   timestamp: 2026-03-19T17:16:38+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AnyUrl, BaseModel, Field


class BeneficiaryType(str, Enum):
    companion_animals = 'companion_animals'
    farmed_animals = 'farmed_animals'
    wild_animals = 'wild_animals'
    unspecified = 'unspecified'


class QuantitativeData(BaseModel):
    value: float | None = Field(..., description='The numerical value of the metric.')
    unit: str = Field(
        ...,
        description="The unit of measurement (e.g., 'animals', 'commitments', 'meals').",
    )


class CounterfactualBaseline(BaseModel):
    description: str = Field(
        ...,
        description='A concise description of the baseline or control group (max 150 chars).',
    )
    value: float | None = Field(
        None, description='The numerical value of the baseline, if available.'
    )


class EvidenceQuality(str, Enum):
    RCT_Meta_Analysis = 'RCT/Meta-Analysis'
    Quasi_Experimental = 'Quasi-Experimental'
    Pre_Post = 'Pre-Post'
    Anecdotal = 'Anecdotal'
    None_ = 'None'


class Timeframe(str, Enum):
    annual = 'annual'
    cumulative = 'cumulative'
    unspecified = 'unspecified'


class InterventionTypeEnum(str, Enum):
    corporate_welfare_campaigns = 'corporate_welfare_campaigns'
    policy_and_legal_advocacy = 'policy_and_legal_advocacy'
    alternative_protein_and_food_tech = 'alternative_protein_and_food_tech'
    scientific_and_welfare_research = 'scientific_and_welfare_research'
    high_volume_spay_neuter = 'high_volume_spay_neuter'
    undercover_investigations_and_exposes = 'undercover_investigations_and_exposes'
    capacity_building_and_movement_growth = 'capacity_building_and_movement_growth'
    individual_rescue_and_sanctuary = 'individual_rescue_and_sanctuary'
    veterinary_care_and_treatment = 'veterinary_care_and_treatment'
    disaster_response_and_emergency_relief = 'disaster_response_and_emergency_relief'
    wildlife_conservation_and_habitat_protection = (
        'wildlife_conservation_and_habitat_protection'
    )
    vegan_outreach_and_dietary_change = 'vegan_outreach_and_dietary_change'
    humane_education_and_community_support = 'humane_education_and_community_support'
    other = 'other'


class Value(str, Enum):
    pure_animal_advocacy = 'pure_animal_advocacy'
    multi_domain_operations = 'multi_domain_operations'


class InterventionType(str, Enum):
    corporate_welfare_campaigns = 'corporate_welfare_campaigns'
    policy_and_legal_advocacy = 'policy_and_legal_advocacy'
    alternative_protein_and_food_tech = 'alternative_protein_and_food_tech'
    scientific_and_welfare_research = 'scientific_and_welfare_research'
    high_volume_spay_neuter = 'high_volume_spay_neuter'
    undercover_investigations_and_exposes = 'undercover_investigations_and_exposes'
    capacity_building_and_movement_growth = 'capacity_building_and_movement_growth'
    individual_rescue_and_sanctuary = 'individual_rescue_and_sanctuary'
    veterinary_care_and_treatment = 'veterinary_care_and_treatment'
    disaster_response_and_emergency_relief = 'disaster_response_and_emergency_relief'
    wildlife_conservation_and_habitat_protection = (
        'wildlife_conservation_and_habitat_protection'
    )
    vegan_outreach_and_dietary_change = 'vegan_outreach_and_dietary_change'
    humane_education_and_community_support = 'humane_education_and_community_support'
    other = 'other'


class SourceType(str, Enum):
    attached_report = 'attached_report'
    web_search = 'web_search'


class Source(BaseModel):
    source_type: SourceType = Field(
        ..., description='The strict category of the source document.'
    )
    source_index: int | None = Field(
        None,
        description='For attached PDF document sources, the 0-based index of the attached document (among all attached documents) where the data was found.',
    )
    page_number: int | None = Field(
        None,
        description='For attached PDF document sources, the 1-based absolute index of the page (in that attached document) where the data was found.',
    )
    search_result_index: int | None = Field(
        None,
        description='For web_search sources, the 0-based index of the search result snippet used.',
    )
    quote: str | None = Field(
        ...,
        description='The exact verbatim wording quoted from the source, used for verification and text-fragment generation.',
    )
    resolved_url: AnyUrl | None = Field(
        ...,
        description='The fully resolved deep-link URL (e.g., with #page=N or #:~:text=...) to the specific source evidence. This is populated programmatically.',
    )


class Beneficiary(BaseModel):
    location: str = Field(
        ...,
        description="Geographic area of the beneficiaries (e.g., 'Hong Kong', 'Yuen Long District').",
    )
    population: float | None = Field(
        ...,
        description='The exact number of actual, individual animals directly aided during the reporting year (e.g., through rescue, vaccination, or sheltering). Must NOT include projected, estimated, or indirect populations derived from legislative, policy, or corporate welfare victories.',
    )
    beneficiary_type: BeneficiaryType = Field(
        ..., description='The primary category of animal beneficiaries.'
    )
    source: Source | None = None


class Metric(BaseModel):
    metric_name: str = Field(
        ...,
        description="A descriptive name for the metric (e.g., 'Animals Rescued', 'Cage-Free Commitments Secured').",
    )
    quantitative_data: QuantitativeData
    context_qualifier: str = Field(
        ...,
        description='A brief, clear summary providing context for the metric (max 150 chars).',
    )
    counterfactual_baseline: CounterfactualBaseline = Field(
        ..., description='What would have happened if the charity did not intervene.'
    )
    evidence_quality: EvidenceQuality = Field(
        ...,
        description='The quality of evidence supporting the metric, based on a strict hierarchy.',
    )
    timeframe: Timeframe = Field(
        ...,
        description="The temporal scope of the metric, indicating if it's an annual or cumulative figure.",
    )
    source: Source | None


class SignificantEvent(BaseModel):
    event_name: str = Field(
        ..., description='The name of the specific program or intervention.'
    )
    summary: str = Field(
        ..., description='A brief summary of the event or intervention.'
    )
    intervention_type: list[InterventionTypeEnum] = Field(
        ...,
        description='The categories of the intervention. Multiple selections are allowed.',
    )
    intervention_type_other_description: str | None = Field(
        ...,
        description="If 'other' is selected for intervention_type, provide a 3-5 word summary (max 100 chars) of the intervention. Otherwise, this should be null.",
    )
    timeframe: Timeframe = Field(
        ...,
        description='The temporal scope of the event, indicating if it occurred in the reporting year or is a historical milestone.',
    )
    source: Source | None


class OperatingScope(BaseModel):
    value: Value | None = None
    source: Source | None = None


class ExplicitUnitCost(BaseModel):
    intervention_type: InterventionType
    amount: float | None
    currency: str | None = Field(
        ...,
        description='The 3-letter ISO 4217 code of the currency (e.g., USD, HKD, INR).',
    )
    description: str | None
    source: Source | None


class Context(BaseModel):
    operating_scope: OperatingScope | None = Field(
        None, description="Classification of the charity's primary operational focus."
    )
    explicit_unit_costs: list[ExplicitUnitCost] | None = Field(
        None,
        description='Array of unit costs explicitly stated by the charity, each linked to a specific intervention type.',
    )


class UnintendedConsequencesReported(BaseModel):
    value: bool | None = None
    source: Source | None = None


class EuthanasiaStatisticsReported(BaseModel):
    value: bool | None = None
    source: Source | None = None


class TransparencyIndicators(BaseModel):
    unintended_consequences_reported: UnintendedConsequencesReported | None = Field(
        None,
        description='Disclosure of unintended negative impacts or failures. (Only self-reported disclosure (from the attached reports) counts)',
    )
    euthanasia_statistics_reported: EuthanasiaStatisticsReported | None = Field(
        None,
        description='Disclosure of exact euthanasia or live-release rates. (Only self-reported disclosure (from the attached reports) counts)',
    )


class Impact(BaseModel):
    beneficiaries: list[Beneficiary] = Field(
        ...,
        description='Demographics of the primary beneficiaries, tailored for animal advocacy.',
    )
    metrics: list[Metric] = Field(
        ..., description='A list of specific, quantifiable impact metrics.'
    )
    significant_events: list[SignificantEvent] = Field(
        ..., description='Key interventions or events undertaken by the charity.'
    )
    context: Context = Field(
        ...,
        description="Contextual information about the charity's operations and stated costs.",
    )
    transparency_indicators: TransparencyIndicators = Field(
        ...,
        description='Indicators of operational transparency and epistemic humility.',
    )
