# generated by datamodel-codegen:
#   filename:  impact_interventions.schema.json
#   timestamp: 2026-04-19T08:31:52+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AnyUrl, BaseModel, Field


class InterventionTypeEnum(str, Enum):
    corporate_welfare_campaigns = 'corporate_welfare_campaigns'
    policy_and_legal_advocacy = 'policy_and_legal_advocacy'
    alternative_protein_and_food_tech = 'alternative_protein_and_food_tech'
    scientific_and_welfare_research = 'scientific_and_welfare_research'
    high_volume_spay_neuter = 'high_volume_spay_neuter'
    undercover_investigations_and_exposes = 'undercover_investigations_and_exposes'
    capacity_building_and_movement_growth = 'capacity_building_and_movement_growth'
    individual_rescue_and_sanctuary = 'individual_rescue_and_sanctuary'
    veterinary_care_and_treatment = 'veterinary_care_and_treatment'
    disaster_response_and_emergency_relief = 'disaster_response_and_emergency_relief'
    wildlife_conservation_and_habitat_protection = (
        'wildlife_conservation_and_habitat_protection'
    )
    vegan_outreach_and_dietary_change = 'vegan_outreach_and_dietary_change'
    humane_education_and_community_support = 'humane_education_and_community_support'
    other = 'other'


class PrimaryInterventionType(str, Enum):
    corporate_welfare_campaigns = 'corporate_welfare_campaigns'
    policy_and_legal_advocacy = 'policy_and_legal_advocacy'
    alternative_protein_and_food_tech = 'alternative_protein_and_food_tech'
    scientific_and_welfare_research = 'scientific_and_welfare_research'
    high_volume_spay_neuter = 'high_volume_spay_neuter'
    undercover_investigations_and_exposes = 'undercover_investigations_and_exposes'
    capacity_building_and_movement_growth = 'capacity_building_and_movement_growth'
    individual_rescue_and_sanctuary = 'individual_rescue_and_sanctuary'
    veterinary_care_and_treatment = 'veterinary_care_and_treatment'
    disaster_response_and_emergency_relief = 'disaster_response_and_emergency_relief'
    wildlife_conservation_and_habitat_protection = (
        'wildlife_conservation_and_habitat_protection'
    )
    vegan_outreach_and_dietary_change = 'vegan_outreach_and_dietary_change'
    humane_education_and_community_support = 'humane_education_and_community_support'
    other = 'other'


class Timeframe(str, Enum):
    annual = 'annual'
    cumulative = 'cumulative'
    unspecified = 'unspecified'


class Value(str, Enum):
    pure_animal_advocacy = 'pure_animal_advocacy'
    multi_domain_operations = 'multi_domain_operations'


class InterventionType(str, Enum):
    corporate_welfare_campaigns = 'corporate_welfare_campaigns'
    policy_and_legal_advocacy = 'policy_and_legal_advocacy'
    alternative_protein_and_food_tech = 'alternative_protein_and_food_tech'
    scientific_and_welfare_research = 'scientific_and_welfare_research'
    high_volume_spay_neuter = 'high_volume_spay_neuter'
    undercover_investigations_and_exposes = 'undercover_investigations_and_exposes'
    capacity_building_and_movement_growth = 'capacity_building_and_movement_growth'
    individual_rescue_and_sanctuary = 'individual_rescue_and_sanctuary'
    veterinary_care_and_treatment = 'veterinary_care_and_treatment'
    disaster_response_and_emergency_relief = 'disaster_response_and_emergency_relief'
    wildlife_conservation_and_habitat_protection = (
        'wildlife_conservation_and_habitat_protection'
    )
    vegan_outreach_and_dietary_change = 'vegan_outreach_and_dietary_change'
    humane_education_and_community_support = 'humane_education_and_community_support'
    other = 'other'


class SourceType(str, Enum):
    attached_report = 'attached_report'


class Source(BaseModel):
    source_type: SourceType = Field(
        ..., description='The strict category of the source document.'
    )
    source_index: int | None = Field(
        None,
        description='For attached PDF document sources, the 0-based index of the attached document (among all attached documents) where the data was found.',
    )
    page_number: int | None = Field(
        None,
        description='For attached PDF document sources, the 1-based absolute index of the page (in that attached document) where the data was found.',
    )
    quote: str | None = Field(
        ...,
        description='The exact verbatim wording quoted from the source, used for verification and text-fragment generation.',
    )
    resolved_url: AnyUrl | None = Field(
        ...,
        description='The fully resolved deep-link URL (e.g., with #page=N or #:~:text=...) to the specific source evidence. This is populated programmatically.',
    )


class SignificantEvent(BaseModel):
    event_name: str
    summary: str
    intervention_type: list[InterventionTypeEnum]
    intervention_type_other_description: str | None
    primary_intervention_type: PrimaryInterventionType = Field(
        ...,
        description='The primary intervention type for this event, used for leverage multiplier resolution.',
    )
    timeframe: Timeframe
    source: Source | None


class OperatingScope(BaseModel):
    value: Value | None = None
    source: Source | None = None


class ExplicitUnitCost(BaseModel):
    intervention_type: InterventionType
    amount: float | None
    currency: str | None
    description: str | None
    source: Source | None


class Context(BaseModel):
    operating_scope: OperatingScope
    explicit_unit_costs: list[ExplicitUnitCost] = Field(
        ...,
        description='Array of unit costs explicitly stated by the charity, each linked to a specific intervention type.',
    )


class ImpactInterventions(BaseModel):
    significant_events: list[SignificantEvent] = Field(
        ...,
        description='Key interventions or events undertaken by the charity, sorted in descending order of significance.',
    )
    context: Context
