# generated by datamodel-codegen:
#   filename:  impact_metrics.schema.json
#   timestamp: 2026-04-22T17:44:29+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AnyUrl, BaseModel, Field


class QuantitativeData(BaseModel):
    value: float | None
    unit: str
    unit_is_individual_animal: bool | None = Field(
        None,
        description="Whether the unit refers to an individual animal (e.g., 'lives saved', 'vaccinations administered') or a different quantity (e.g., 'tons of feed saved', 'fund raised', 'eggs laid'). This is important for accurate aggregation and comparison across metrics.",
    )


class Timeframe(str, Enum):
    annual = 'annual'
    cumulative = 'cumulative'
    unspecified = 'unspecified'


class SourceType(str, Enum):
    attached_report = 'attached_report'


class Source(BaseModel):
    source_type: SourceType = Field(
        ..., description='The strict category of the source document.'
    )
    source_index: int = Field(
        ...,
        description='For attached PDF document sources, the 0-based index of the attached document (among all attached documents) where the data was found.',
    )
    page_number: int = Field(
        ...,
        description='For attached PDF document sources, the 1-based absolute index of the page (in that attached document) where the data was found.',
    )
    quote: str | None = Field(
        ...,
        description='The exact verbatim wording quoted from the source, used for verification and text-fragment generation.',
    )
    resolved_url: AnyUrl | None = Field(
        ...,
        description='The fully resolved deep-link URL (e.g., with #page=N or #:~:text=...) to the specific source evidence. This is populated programmatically.',
    )


class CounterfactualBaseline(BaseModel):
    value: float | None
    source: Source | None


class Metric(BaseModel):
    metric_name: str
    species_key: str = Field(
        ...,
        description='The species key for moral weight lookup. [ALLOWED VALUES: {{CONCATENATED_SPECIES_KEY_VALUES}}]',
    )
    intervention_key: str = Field(
        ...,
        description='The intervention key for leverage multiplier lookup. [ALLOWED VALUES: {{CONCATENATED_INTERVENTION_KEY_VALUES}}]',
    )
    quantitative_data: QuantitativeData
    context_qualifier: str
    counterfactual_baseline: CounterfactualBaseline
    evidence_quality: str = Field(
        ...,
        description='The quality of evidence supporting the metric. [ALLOWED VALUES: {{CONCATENATED_EVIDENCE_KEY_VALUES}}]',
    )
    timeframe: Timeframe
    source: Source | None


class ImpactMetrics(BaseModel):
    metrics: list[Metric] = Field(
        ...,
        description='A list of specific, quantifiable impact metrics, sorted in descending order of significance.',
    )
