# generated by datamodel-codegen:
#   filename:  meta.schema.json
#   timestamp: 2026-03-17T07:45:27+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Metadata(BaseModel):
    chinese_name: str | None = Field(
        ..., description='The official Chinese name of the charity.'
    )
    aliases: list[str] = Field(
        ...,
        description='A list of commonly used acronyms or alternative names for the charity',
    )
    domains: list[str] = Field(
        ...,
        description='A list of official website domains associated with the charity.',
    )
    registration_id: str | None = Field(
        ...,
        description="The official non-profit registration identifier for the charity's jurisdiction (e.g., HK s88 ID, US EIN, UK Charity Number).",
    )
