# generated by datamodel-codegen:
#   filename:  search.schema.json
#   timestamp: 2026-03-17T07:45:30+00:00

from __future__ import annotations

from pydantic import AnyUrl, BaseModel, Field


class SearchResult(BaseModel):
    original_text: str = Field(
        ..., description='Original text/snippets from the search.'
    )
    url: AnyUrl = Field(..., description='URL of the search result.')


class Search(BaseModel):
    search_results: list[SearchResult] = Field(..., description='')
